### ISSUE TITLE
Cannot login - `indigenous-android://` intent does not appear to work

### ISSUE THREAD

**Issue by jamietanna** [IndiePass/indiepass-android#440]
When trying to log in, I return back to https://indiepass.app/android-callback but then the app doesn't log in.

Even trying to click the `If IndiePass is not opening, click here`, doesn't load

:thinking: 

Seeing this on v0.84

**Comment by marksuth** [comment]
Hey,

I've tried replicating the issue on an Android 13 device using Chrome which worked OK, would it possible to get a bit of insight as to the Android version you're using, and which web browser you're using on the device so I can do some digging.

Thanks in advance

Cheers
Mark

**Comment by jamietanna** [comment]
Hmm yeah good shout, I've been using Firefox Nightly Version 117.0a1 on Android 13, looks like it works with Chrome 😥 so at least I can use the app now 👏🏽
